### ISSUE TITLE
Over-riding values still isn't completely working as expected

### ISSUE THREAD

**Issue by Jaymon** [Jaymon/captain#75]
```python
class Foo(Command):
 @arg(
        "foos",
        metavar="FOO",
        nargs="*",
        dest="foo_names",
        help="foo help 1"
    )
    def handle(self, *args, **kwargs): pass

class Bar(Command):
 @args(Foo)
 @arg(
        "foos",
        nargs="+",
        dest="foo_names",
        help="foo help 2"
    )
    def handle(self, *args, **kwargs): pass
```

I would expect the merged `foo_names` to roughly look like this:

```
args:
  foos

kwargs:
  nargs: +
  dest: foo_names
  help: foo help 2
```

But that didn't seem to be the case, I had to add `metavar` to the child one to get it to look as expected.
